### ISSUE TITLE
Unable to install native, prebuilt, binary gems on Windows anymore

### ISSUE THREAD

**Issue by mcorino** [rubygems/rubygems#1152]
I have a problem attempting to install prebuilt (platform specific) gems on Windows either with Ruby 2.0.0 64bit & Rubygems 2.0.14 or with Ruby 2.1.5 64bit & Rubygems 2.4.5.

I test these gems on a local gemserver which correctly reports the gems available when using "gem search" listing them like:

"r2corba_ext20 (1.5.1 x64-mingw32, 1.4.1 x64-mingw32 x86-mingw32)

but when I attempt to install the 1.5.1 version of the gem I get the message that installation failed since the gem could not be found locally or remote!

I am able to "gem fetch" the gem though which results in a locally stored r2corba_ext20-1.5.1-x64-mingw32.gem file which I am able to install using "gem install <filename>".
When next attempting to install another gem listing the prebuilt (and now locally installed) gem as a dependency it again fails with the message that the gem could not be found locally or remote.

Thinking this may have something to do with my gems I tested this with a random other platform specific gem for x64-mingw32 (not mine!) on rubygems.org, "tiny_tds", and found that that one fails in the same way.

Something is definitely not right here. Any ideas what?

**Comment by drbrain** [comment]
What does `gem env` say?

I looked at your source, but couldn't immediately see where you set the platform for the gem specification.  Can you point out that line?

**Comment by ryanatball** [comment]
This is probably related to #1120

**Comment by mcorino** [comment]
`gem env` for the Ruby 2.0.0 installation says:

RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14
  - RUBY VERSION: 2.0.0 (2014-11-13 patchlevel 598) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby200/lib/ruby/gems/2.0.0
  - RUBY EXECUTABLE: C:/Ruby200/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby200/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby200/lib/ruby/gems/2.0.0
     - C:/Users/build/.gem/ruby/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "benchmark" => false
  - REMOTE SOURCES:
     - https://rubygems.org/

for the Ruby 2.1.5 installation it says:

RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.4
  - RUBY VERSION: 2.1.5 (2014-11-13 patchlevel 273) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby215/lib/ruby/gems/2.1.0
  - RUBY EXECUTABLE: C:/Ruby215/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby215/bin
  - SPEC CACHE DIRECTORY: C:/Users/build/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby215/lib/ruby/gems/2.1.0
     - C:/Users/build/.gem/ruby/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "benchmark" => false
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Ruby215\bin
     - C:\ProgramData\Oracle\Java\javapath
     - C:\mingw64\bin
     - C:\mingw64\x86_64-w64-mingw32\lib
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Windows\SysWOW64
     - C:\Perl64\site\bin
     - C:\Perl64\bin
     - C:\MingW\msys\1.0\bin
     - C:\MingW\bin
     - C:\Program Files (x86)\Git\cmd
     - C:\Ruby200\bin
     - C:\Tools

What source are you referring to?

**Comment by mcorino** [comment]
With regard to #1120 please note that I was able to successfully `gem fetch` the gem. It's installing from a remote repository that fails.

**Comment by mcorino** [comment]
This is the gemspec extracted from the Ruby 2.0.0 gem:
```
--- !ruby/object:Gem::Specification
name: r2corba_ext20
version: !ruby/object:Gem::Version
  version: 1.5.1
platform: x64-mingw32
authors:
- Martin Corino
autorequire: 
bindir: bin
cert_chain: []
date: 2015-01-23 00:00:00.000000000 Z
dependencies: []
description: OMG CORBA v. 3.3 compliant CORBA language mapping implementation for
  Ruby. Depends on ridl gem for providing native Ruby IDL compiler. (extension binaries)
email: mcorino@remedy.nl
executables: []
extensions: []
extra_rdoc_files: []
files:
- ext/libACE.dll
- ext/libTAO.dll
- ext/libTAO_TypeCodeFactory.dll
- ext/libTAO_IFR_Client.dll
- ext/libTAO_DynamicInterface.dll
- ext/libTAO_Messaging.dll
- ext/libTAO_PI.dll
- ext/libTAO_CodecFactory.dll
- ext/libTAO_Codeset.dll
- ext/libTAO_DynamicAny.dll
- ext/libTAO_Valuetype.dll
- ext/libTAO_PortableServer.dll
- ext/libTAO_AnyTypeCode.dll
- ext/libTAO_BiDirGIOP.dll
- ext/libTAO_IORTable.dll
- ext/libTAO_ImR_Client.dll
- ext/libr2tao.so
- ext/libr2taow.so
- ext/librpoa.so
- ext/librpoaw.so
- ext/librpol.so
- ext/librpolw.so
homepage: https://osportal.remedy.nl/projects/r2corba
licenses:
- R2CORBA
- ACE
metadata: {}
post_install_message: 
rdoc_options:
- --exclude=\.dll
- --exclude=\.so
- --exclude=\.pidlc
require_paths:
- ext
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - '>='
    - !ruby/object:Gem::Version
      version: 2.0.0
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - '>='
    - !ruby/object:Gem::Version
      version: '0'
requirements: []
rubyforge_project: 
rubygems_version: 2.0.14
signing_key: 
specification_version: 4
summary: CORBA language mapping implementation for Ruby (extension binaries)
test_files: []
```
