### ISSUE TITLE
RubyGems and Ruby master CI - example workflow

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3497]
Don't know whether it is desired to have it a cron job, as it doesn't take that long.

The following passes, it's labelled as a cron job, but runs on push/PR.

```yml
name: daily

on: [push, pull_request]

jobs:
  daily:
    timeout-minutes: 10
    name: RG Cron ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu  , ruby: head  }
          - { os: macos   , ruby: head  }
          - { os: windows , ruby: mingw }
          - { os: windows , ruby: mswin }
          
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name:  Setup
        shell: pwsh
        run:   |
          # 2020-04-08 jaro_winkler 1.5.4 will not compile on mswin
          if ('${{ matrix.ruby }}' -eq 'mswin') {
            gem install builder -N
          } else {
            rake setup
          }
        
      - name: Test rubygems
        run:  rake test
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).
