### ISSUE TITLE
 ubuntu-bundler.yml - matrix excludes

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3558]
Re the matrix excludes in ubuntu-bundler.yml

https://github.com/rubygems/rubygems/blob/492496af849f564e96374671f3f3261452268e3d/.github/workflows/ubuntu-bundler.yml#L14-L37

They could be formatted as below, which some may consider easier to read:
```yaml
      matrix:
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5, 2.7.0 ]
        rgv: [ v2.5.2, v2.6.14, v2.7.10, v3.0.6, v3.1.2, .. ]
        exclude:
          - { ruby: 2.4.9 , rgv: v2.5.2  }
          - { ruby: 2.5.7 , rgv: v2.5.2  }
          - { ruby: 2.5.7 , rgv: v2.6.14 }
          - { ruby: 2.6.5 , rgv: v2.5.2  }
          - { ruby: 2.6.5 , rgv: v2.6.14 }
          - { ruby: 2.6.5 , rgv: v2.7.10 }
          - { ruby: 2.7.0 , rgv: v2.5.2  }
          - { ruby: 2.7.0 , rgv: v2.6.14 }
          - { ruby: 2.7.0 , rgv: v2.7.10 }
          - { ruby: 2.7.0 , rgv: v3.0.6  }
```
