### ISSUE TITLE
NoMethodError: undefined method `full_name' for nil:NilClass bug that should have been fixed

### ISSUE THREAD

**Issue by jugdx** [rubygems/rubygems#5422]
Hello there 👋🏼 ,

### Context 

I post here an error that should have been fixed since December last year, but it seems that we can still have it.
[Here](https://github.com/rubygems/rubygems/pull/5092) is the fix I'm talking about.
This should have been integrated in the [2.2.33](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.33) version. We are using the [2.3.9](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.9) one so the fix should still be there...

### Additional information

This is for an iOS application using `Fastlane`, we have lots of script in Ruby + Shell + YML for Github Actions.
We are migrating from Bitrise to Github so I'm testing our `Release` flow.
The error happen when we execute the `bundle update fastlane`.

I'm posting into the following toggles all the details I have about this.

<details>
<summary>Part of the Release.yml (Github Action)</summary>

```yml
generate_release:
    name: 'Create new release'
    runs-on: macos-11
    outputs:
      jiraIssueKey: ${{ env.ISSUE_KEY }} # Env Variable set at the end of the release flow, via Fastlane's "_release_ci" lane
      rcNumber: ${{ env.RC_NUMBER }} # Env Variable set at the end of the release flow, via Fastlane's "_release_ci" lane

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_XX }} 

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # Runs a single command using the runners shell
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Project
        run: |
          ci/_setup.sh
          ci/set-slack-target.sh

      - name: Execute release flow
        env:
          RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
          RELEASE_OWNER_EMAIL: ${{ github.event.inputs.releaseOwnerEmail }}
        run: ci/_release.sh

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-appstore
          path: iOS-submission/

      - name: Post
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          CI_JOB_STATUS: ${{ job.status }}
        run: ci/_post.sh
```
</details>

<details>
<summary>Error</summary>

```
# ..... Some other lines of `Using ....`
Using xcode-install 2.8.0
--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `full_name' for nil:NilClass
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:123:in `each'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:122:in `each'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:100:in `call'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer.rb:259:in `install_in_parallel'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer.rb:209:in `install'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer.rb:89:in `block in run'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/process_lock.rb:9:in `open'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/process_lock.rb:9:in `lock'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer.rb:71:in `run'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/installer.rb:23:in `install'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli/update.rb:78:in `run'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli.rb:303:in `block in update'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/settings.rb:131:in `temporary'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli.rb:302:in `update'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/bin/bundle:23:in `load'
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/bin/bundle:23:in `<main>'
```
</details>

<details>
<summary>Context</summary>

## Environment

```
Bundler       2.3.9
  Platforms   ruby, x86_64-darwin-19
Ruby          2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin-19]
  Full Path   /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/bin/ruby
  Config Dir  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/etc
RubyGems      3.0.3
  Gem Home    /Users/runner/work/app/app/vendor/bundle/ruby/2.6.0
  Gem Path    /Users/runner/work/app/app/vendor/bundle/ruby/2.6.0
  User Home   /Users/runner
  User Path   /Users/runner/.gem/ruby/2.6.0
  Bin Dir     /Users/runner/work/app/app/vendor/bundle/ruby/2.6.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1h  22 Sep 2020
  Loaded      OpenSSL 1.1.1h  22 Sep 2020
  Cert File   /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/openssl/ssl/cert.pem
  Cert Dir    /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/openssl/ssl/certs
Tools         
  Git         2.35.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-03-09
Git SHA           7f90c0083a
Released Version  true
```

## Bundler settings

```
deployment
  Set for your local app (/Users/runner/work/app/app/.bundle/config): true
jobs
  Set for your local app (/Users/runner/work/app/app/.bundle/config): 4
path
  Set for your local app (/Users/runner/work/app/app/.bundle/config): "/Users/runner/work/app/app/vendor/bundle"
```

### Gemfile

```ruby
# frozen_string_literal: true
# A sample Gemfile
source 'https://rubygems.org/'

ruby '~> 2.6.5'
gem 'cocoapods'
gem 'jira-ruby'
gem 'fastlane'
gem 'phraseapp-ruby', '~> 1.6'
gem 'faraday'
gem 'faraday_middleware'
gem "xcode-install"
gem 'aws-sdk', '~> 3'
gem 'uuid'
gem 'json'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
```
</details>

### Did you try upgrading rubygems & bundler?

Of course I've tried this solution:
> Running `gem update --system` should get both installed on your system, and then
`bundle update --bundler` should change your lockfile to use the new version of
bundler that was just installed.

I also saw that the fix has been integrated to the `2.2.33` version so I use now the `2.3.9` that should also have the fix...
So I'm up to date to the last `2.x` version of Bundler.

---

When we were using Bitrise we didn't have that issue.. So maybe that can comes from GitHub but anything I search about this on the web... I end up to the bundler issue I linked at the top and I don't find any solution. This is why I'm also trying here to see with you, if the fix is still active or if maybe there's still a way to fall into that bug.

**Comment by deivid-rodriguez** [comment]
Thanks, can you post steps to reproduce the issue?

**Comment by Undo1** [comment]
I just saw this on a common Rails webapp, on bundle install after adding the Stripe gem. Same traceback, bundler v2.3.6.

Apple Silicon / macOS 12.3; everything worked yesterday. Private project so I won't just paste the error report, but I'll grab anything specific out of it you want.

**Comment by jugdx** [comment]
@deivid-rodriguez : I'm very sorry but I can't do any repo with that content as this repo is owned by my company and the content is private!
And Yes, this is only reproductible under Github Actions...

@Undo1 : I'm gonna test your solution and let you know if it worked and fixed the issue. 🙏🏼

**Comment by deivid-rodriguez** [comment]
@jugdx I'm not asking you to make your private repo public, but you have already published your `Gemfile` and configuration, I'm asking you to extract that (and anything else needed) to a minimal repository that reproduces the issue.

**Comment by jugdx** [comment]
Ok sorry! I got it.
I won't have time until this week-end but I'll try to do it asap.
Thanks for your help.

**Comment by jugdx** [comment]
We have a workaround ( @Undo1 ) you put us on the way. 

```yml

      # Runs a single command using the runners shell
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false # this was true before! 

      - name: Setup Project
        run: |
          ci/_setup.sh
          ci/set-slack-target.sh
```
We set the `bundler-cache` to false! 
But it didn't fixed everything! By doing so, the `bundle install` command is not called anymore.
So I just called it in the following `_setup.sh` 

```bash
#!/usr/bin/env bash
set -ex

bundle install
bundle exec fastlane install # we only had this line before! 
```

(CC: @deivid-rodriguez ! Do you still need a fake repo with the minimu if I end up to the same error or these steps to fix/have a workaround are helpful to investigate? )
