### ISSUE TITLE
gem push results in "No Stairway, denied!"

### ISSUE THREAD

**Issue by Phrogz** [rubygems/rubygems#627]
I'm trying to push a new version of my gem live. When I do

```
gem push docubot-1.1.1.gem
```

I get a bunch of HTML back including `<h3>No Stairway, denied!</h3>`. You can get the gem from http://phrogz.net/tmp/docubot-1.1.1.gem

Here's the result of looking at the spec:

```
C:\docubot>gem spec docubot-1.1.1.gem
--- !ruby/object:Gem::Specification
name: docubot
version: !ruby/object:Gem::Version
  version: 1.1.1
platform: ruby
authors:
- Gavin Kistner
- Harold Hausman
autorequire:
bindir: bin
cert_chain: []
date: 2013-08-28 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
  name: haml
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: nokogiri
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: kramdown
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: RedCloth
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: minitest
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ! '>='
      - !ruby/object:Gem::Version
        version: '0'
description: DocuBot creates HTML or CHM documentation from a hierarchy of files,
  supporting markups like Markdown, Textile, and Haml.
email: gavin@phrogz.net
executables:
- docubot
extensions: []
extra_rdoc_files: []
files:
- bin/docubot
- lib/docubot/bundle.rb
- lib/docubot/converter.rb
- lib/docubot/converters/haml.rb
- lib/docubot/converters/html.rb
- lib/docubot/converters/markdown.rb
- lib/docubot/converters/raw_code.rb
- lib/docubot/converters/textile.rb
- lib/docubot/glossary.rb
- lib/docubot/index.rb
- lib/docubot/link_tree.rb
- lib/docubot/metasection.rb
- lib/docubot/page.rb
- lib/docubot/shells/default/0_License.md
- lib/docubot/shells/default/Appendix/Glossary.md
- lib/docubot/shells/default/Appendix/Index_Page.md
- lib/docubot/shells/default/Appendix/Table of Contents.md
- lib/docubot/shells/default/index.txt
- lib/docubot/shells/default/_static/logo.png
- lib/docubot/shells/docubot-help/0_License.md
- lib/docubot/shells/docubot-help/1_Getting_Started.md
- lib/docubot/shells/docubot-help/2_Basic_Concepts/0 The Metasection.md
- lib/docubot/shells/docubot-help/2_Basic_Concepts/1 Interpage Links.md
- lib/docubot/shells/docubot-help/2_Basic_Concepts/2 Generating the Output.md
- lib/docubot/shells/docubot-help/2_Basic_Concepts/3 Customizing Templates.md
- lib/docubot/shells/docubot-help/2_Basic_Concepts/4 Adding Images.md
- lib/docubot/shells/docubot-help/2_Basic_Concepts/index.md
- lib/docubot/shells/docubot-help/3_Advanced_Topics/Controlling Glossary.md
- lib/docubot/shells/docubot-help/3_Advanced_Topics/Controlling Indexing.md
- lib/docubot/shells/docubot-help/3_Advanced_Topics/Controlling the Table of Contents.md
- lib/docubot/shells/docubot-help/3_Advanced_Topics/Switching Page Templates.md
- lib/docubot/shells/docubot-help/4_Appendix/Glossary.md
- lib/docubot/shells/docubot-help/4_Appendix/Index_Page.md
- lib/docubot/shells/docubot-help/4_Appendix/Table of Contents.md
- lib/docubot/shells/docubot-help/index.txt
- lib/docubot/shells/docubot-help/_glossary/Template.md
- lib/docubot/shells/docubot-help/_static/glider.png
- lib/docubot/snippet.rb
- lib/docubot/snippets/glossary.rb
- lib/docubot/snippets/index_entries.rb
- lib/docubot/templates/glossary.haml
- lib/docubot/templates/index.haml
- lib/docubot/templates/page.haml
- lib/docubot/templates/section.haml
- lib/docubot/templates/toc.haml
- lib/docubot/templates/top.haml
- lib/docubot/templates/_root/common.css
- lib/docubot/templates/_root/glossary.css
- lib/docubot/templates/_root/glossary.js
- lib/docubot/templates/_root/toc.css
- lib/docubot/templates/_root/toc.js
- lib/docubot/writer.rb
- lib/docubot/writers/chm/hhc.erb
- lib/docubot/writers/chm/hhk.erb
- lib/docubot/writers/chm/hhp.erb
- lib/docubot/writers/chm.rb
- lib/docubot/writers/html.rb
- lib/docubot.rb
- spec/bundle.rb
- spec/chm.rb
- spec/command.rb
- spec/converters.rb
- spec/global.rb
- spec/glossary.rb
- spec/index.rb
- spec/page.rb
- spec/samples/attributes/defaults.haml
- spec/samples/attributes/explicit1.haml
- spec/samples/attributes/explicit2.haml
- spec/samples/attributes/explicit3.md
- spec/samples/attributes/hidden.haml
- spec/samples/attributes/index.md
- spec/samples/collisions/page1.md
- spec/samples/collisions/page1.textile
- spec/samples/collisions/page2.haml
- spec/samples/collisions/page2.html
- spec/samples/collisions/page2.txt
- spec/samples/collisions/page3.bin
- spec/samples/collisions/page3.md
- spec/samples/default_topic/Alpha.md
- spec/samples/default_topic/index.txt
- spec/samples/default_topic/Zeta.md
- spec/samples/default_topic_2/Alpha Space.md
- spec/samples/default_topic_2/index.txt
- spec/samples/default_topic_2/Zeta.md
- spec/samples/files/another.md
- spec/samples/files/BUILDING.txt
- spec/samples/files/common.css
- spec/samples/files/first.textile
- spec/samples/files/index.md
- spec/samples/files/section/foo.jpg
- spec/samples/files/section/page.haml
- spec/samples/files/section/sub section/foo.gif
- spec/samples/files/section/sub section/page.txt
- spec/samples/files/section/sub section/Thumbs.db
- spec/samples/files/_static/foo.ai
- spec/samples/files/_static/foo.png
- spec/samples/files/_static/foo.psd
- spec/samples/files/_static/Thumbs.db
- spec/samples/funkychars/HelloWorld.md
- spec/samples/funkychars/index.txt
- spec/samples/funkychars/Wrapper/0 Ampersand & Spaces Folder/0 Ampersand & Spaces
  File.md
- spec/samples/funkychars/Wrapper/0 Ampersand & Spaces Folder/1 Ampersand_&_Underscores_File.md
- spec/samples/funkychars/Wrapper/0 Ampersand & Spaces Folder/2 ASCII and Spaces File.md
- spec/samples/funkychars/Wrapper/0 Ampersand & Spaces Folder/3 ASCII_and_Underscores_File.md
- spec/samples/funkychars/Wrapper/0 Ampersand & Spaces Folder/4 It's a File!.md
- spec/samples/funkychars/Wrapper/0 Ampersand & Spaces Folder/index.md
- spec/samples/funkychars/Wrapper/1 Ampersand_&_Underscores_Folder/0 Ampersand & Spaces
  File.md
- spec/samples/funkychars/Wrapper/1 Ampersand_&_Underscores_Folder/1 Ampersand_&_Underscores_File.md
- spec/samples/funkychars/Wrapper/1 Ampersand_&_Underscores_Folder/2 ASCII and Spaces
  File.md
- spec/samples/funkychars/Wrapper/1 Ampersand_&_Underscores_Folder/3 ASCII_and_Underscores_File.md
- spec/samples/funkychars/Wrapper/1 Ampersand_&_Underscores_Folder/4 It's a File!.md
- spec/samples/funkychars/Wrapper/1 Ampersand_&_Underscores_Folder/index.md
- spec/samples/funkychars/Wrapper/2 ASCII and Spaces Folder/0 Ampersand & Spaces File.md
- spec/samples/funkychars/Wrapper/2 ASCII and Spaces Folder/1 Ampersand_&_Underscores_File.md
- spec/samples/funkychars/Wrapper/2 ASCII and Spaces Folder/2 ASCII and Spaces File.md
- spec/samples/funkychars/Wrapper/2 ASCII and Spaces Folder/3 ASCII_and_Underscores_File.md
- spec/samples/funkychars/Wrapper/2 ASCII and Spaces Folder/4 It's a File!.md
- spec/samples/funkychars/Wrapper/2 ASCII and Spaces Folder/index.md
- spec/samples/funkychars/Wrapper/3 ASCII_and_Underscores_Folder/0 Ampersand & Spaces
  File.md
- spec/samples/funkychars/Wrapper/3 ASCII_and_Underscores_Folder/1 Ampersand_&_Underscores_File.md
- spec/samples/funkychars/Wrapper/3 ASCII_and_Underscores_Folder/2 ASCII and Spaces
  File.md
- spec/samples/funkychars/Wrapper/3 ASCII_and_Underscores_Folder/3 ASCII_and_Underscores_File.md
- spec/samples/funkychars/Wrapper/3 ASCII_and_Underscores_Folder/4 It's a File!.md
- spec/samples/funkychars/Wrapper/3 ASCII_and_Underscores_Folder/index.md
- spec/samples/funkychars/Wrapper/4 It's a Folder!/0 Ampersand & Spaces File.md
- spec/samples/funkychars/Wrapper/4 It's a Folder!/1 Ampersand_&_Underscores_File.md
- spec/samples/funkychars/Wrapper/4 It's a Folder!/2 ASCII and Spaces File.md
- spec/samples/funkychars/Wrapper/4 It's a Folder!/3 ASCII_and_Underscores_File.md
- spec/samples/funkychars/Wrapper/4 It's a Folder!/4 It's a File!.md
- spec/samples/funkychars/Wrapper/4 It's a Folder!/index.md
- spec/samples/funkychars/_templates/glossary.haml
- spec/samples/funkychars/_templates/page.haml
- spec/samples/funkychars/_templates/section.haml
- spec/samples/funkychars/_templates/top.haml
- spec/samples/funkychars/_templates/_root/bg_green_bar_revised.gif
- spec/samples/funkychars/_templates/_root/close.png
- spec/samples/funkychars/_templates/_root/common.css
- spec/samples/funkychars/_templates/_root/glossary.css
- spec/samples/funkychars/_templates/_root/glossary.js
- spec/samples/funkychars/_templates/_root/nvdevtools.js
- spec/samples/funkychars/_templates/_root/nvidia-logo.gif
- spec/samples/funkychars/_templates/_root/right-sidebar.png
- spec/samples/glossary/Glossary.txt
- spec/samples/glossary/Some Page.md
- spec/samples/glossary/_glossary/complex.haml
- spec/samples/glossary/_glossary/project_x.md
- spec/samples/glossary/_glossary/Simple Term.md
- spec/samples/hierarchy/1/1.1/1.1.1/index.haml
- spec/samples/hierarchy/1/1.1/1.1.1/page.haml
- spec/samples/hierarchy/1/1.1/page.haml
- spec/samples/hierarchy/1/page.haml
- spec/samples/hierarchy/2/2.1/2.1.1/page.haml
- spec/samples/hierarchy/2/2.1/index.haml
- spec/samples/hierarchy/2/2.1/page.haml
- spec/samples/hierarchy/2/page.haml
- spec/samples/hierarchy/main.css
- spec/samples/hierarchy/main.haml
- spec/samples/hierarchy/toc.md
- spec/samples/links/index.txt
- spec/samples/links/one two three.textile
- spec/samples/links/pending.md
- spec/samples/links/root.md
- spec/samples/links/sub1/inner1.md
- spec/samples/links/sub2/bozo.bin
- spec/samples/links/sub2/inner2.md
- spec/samples/links/sub2.md
- spec/samples/ordering/01_Introduction/Content.txt
- spec/samples/ordering/01_Introduction/index.txt
- spec/samples/ordering/0_License.md
- spec/samples/ordering/2_Moar/Content.txt
- spec/samples/ordering/2_Moar/index.txt
- spec/samples/ordering/Appendix/Content.txt
- spec/samples/ordering/Appendix/index.txt
- spec/samples/ordering/index.txt
- spec/samples/simplest/Haml.haml
- spec/samples/simplest/HTML.html
- spec/samples/simplest/Markdown.md
- spec/samples/simplest/Text.txt
- spec/samples/simplest/Textile.textile
- spec/samples/templates/goaway.txt
- spec/samples/templates/onepara_html.html
- spec/samples/templates/onepara_md.md
- spec/samples/templates/twopara_haml.haml
- spec/samples/templates/twopara_textile.textile
- spec/samples/templates/_templates/404.haml
- spec/samples/templates/_templates/doubler.haml
- spec/samples/templates/_templates/page.haml
- spec/samples/titles/1 First One.txt
- spec/samples/titles/2_Second_One.txt
- spec/samples/titles/3_renamed.txt
- spec/samples/titles/4 Fourth_One.txt
- spec/samples/titles/5_Fifth One.txt
- spec/samples/titles/6.1 More.md
- spec/samples/titles/911.txt
- spec/samples/titles/index.txt
- spec/samples/underscores/Home.md
- spec/samples/underscores/subsection/_andignoreme.md
- spec/samples/underscores/_ignoreme.md
- spec/samples/underscores/_static/Foo/_ignoremore.txt
- spec/samples/underscores/_static/_Bar/_ignoreevenmore.txt
- spec/templates.rb
- spec/toc.rb
- spec/writer/chm.rb
- spec/writer/html.rb
- spec/_all.rb
- spec/_helper.rb
homepage: http://github.com/Phrogz/docubot
licenses: []
metadata: {}
post_install_message:
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ! '>='
    - !ruby/object:Gem::Version
      version: '0'
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ! '>='
    - !ruby/object:Gem::Version
      version: '0'
requirements:
- Windows with HTML Help Workshop installed and hhc.exe in the %PATH%.
- Haml gem for template interpretation.
- Nokogiri gem for parsing HTML after creation (and manipulating).
- kramdown gem for Markdown conversion.
- RedCloth gem for Textile conversion.
- MiniTest gem for running specifications.
rubyforge_project:
rubygems_version: 2.0.7
signing_key:
specification_version: 4
summary: Create documentation from a hierarchy of text files.
test_files:
- spec/_all.rb
```
