### ISSUE TITLE
Running `gem install` on a directory with non-tar ".gem" files will result in an error

### ISSUE THREAD

**Issue by dearblue** [rubygems/rubygems#7049]
### Describe the problem as clearly as you can

When I run `gem install` on a directory with non-tar ".gem" files, I get an error and nothing gets installed.
The workaround is to use the explicit `-r` (`--remote`) switch.
`gem update` will only print an error as well.

### Did you try upgrading RubyGems?

Yes.

### Post steps to reproduce the problem

I use `pkg install devel/ruby-gems` on FreeBSD 13.2/amd64.
And, prepare a file with ".gem" extension in an arbitrary directory.

```console
% ruby -e 'File.binwrite "HONYARARA.gem", Random.bytes(4096)'
```

\# I noticed this problem when I tried it on the https://github.com/mruby/mgem-list.git clone directory.

### Which command did you run?

```
gem install rake
```

The actual gem name can be anything.

### What were you expecting to happen?

I expected the specified gem package to be installed.

### What actually happened?

```console
% sudo gem install rake
ERROR:  While executing gem ... (ArgumentError)
    "4\xEB\xFC\xCA\xB8%UL" is not an octal string
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/tar_header.rb:130:in `strict_oct'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/tar_header.rb:108:in `from'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/tar_reader.rb:53:in `each'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/tar_reader.rb:80:in `find'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/tar_reader.rb:80:in `seek'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package.rb:558:in `read_checksums'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package.rb:618:in `block (2 levels) in verify'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/tar_reader.rb:23:in `new'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package.rb:617:in `block in verify'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/file_source.rb:30:in `open'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package/file_source.rb:30:in `with_read_io'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package.rb:616:in `verify'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/package.rb:597:in `spec'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/source/local.rb:48:in `block in load_specs'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/source/local.rb:43:in `each'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/source/local.rb:43:in `load_specs'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/source/local.rb:81:in `find_gem'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/resolver/installer_set.rb:163:in `find_all'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/resolver/installer_set.rb:62:in `add_always_install'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/dependency_installer.rb:319:in `resolve_dependencies'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/commands/install_command.rb:206:in `install_gem'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/commands/install_command.rb:231:in `block in install_gems'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/commands/install_command.rb:224:in `each'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/commands/install_command.rb:224:in `install_gems'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/commands/install_command.rb:170:in `execute'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/command.rb:328:in `invoke_with_build_args'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/command_manager.rb:253:in `invoke_command'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/command_manager.rb:193:in `process_args'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/command_manager.rb:151:in `run'
        /usr/local/lib/ruby/site_ruby/3.1/rubygems/gem_runner.rb:52:in `run'
        /usr/local/bin/gem:12:in `<main>'
```

### Run `gem env` and paste the output below

```yaml
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.20
  - RUBY VERSION: 3.1.4 (2023-03-30 patchlevel 223) [amd64-freebsd13]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/3.1
  - USER INSTALLATION DIRECTORY: /usr/home/dearblue/.local/share/gem/ruby/3.1
  - RUBY EXECUTABLE: /usr/local/bin/ruby31
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /usr/home/dearblue/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - amd64-freebsd-13
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/3.1
     - /usr/home/dearblue/.local/share/gem/ruby/3.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /usr/games
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/home/dearblue/bin
```

### Additional information

It might be better to simply ignore ".gem" files that have problems reading.
I'm not sure if it is necessary to use the `-V` switch to warn in that case.
