### ISSUE TITLE
LoadError: psych.so cannot be found when running bundle install on Ruby 2.7.2 in Docker container on Apple M3

### ISSUE THREAD

**Issue by chinhhq-0603** [rubygems/rubygems#8098]
### Describe the problem as clearly as you can

I'm encountering an issue when running bundle install on an Apple M3 machine. The error message indicates that the psych.so file cannot be found. Here is the specific error message:
```
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': /usr/local/bundle/gems/psych-3.3.1/lib/psych.so: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/psych-3.3.1/lib/psych.so (LoadError)
```

### Post steps to reproduce the problem

1. docker compose file
```
version: "3"
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: containers/rails/Dockerfile
      args:
        RUBY_VERSION: "2.7.2"
    env_file:
      - "./.env.dev"
    volumes:
      - .:/webapp:cached
      - bundle-data:/usr/local/bundle
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - redis
      - db_primary
      - db_readonly
      - localstack
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  public-data:
  bundle-data:
  tmp-data:
  log-data:
  db-primary-data:
  db-readonly-data:
  localstack-data:
....
```

2. Dockerfile

```
ARG RUBY_VERSION
FROM ruby:$RUBY_VERSION
ENV LANG C.UTF-8

ARG APP_PATH
ARG APP_PORT

RUN set -x
RUN apt-get update -qq && \
  apt-get install -y \
  nodejs \
  vim \
  curl \
  libpq-dev \
  postgresql-client \
  pandoc \
  fonts-ipafont \
  libyaml-dev \
  && \
  rm -rf /var/lib/apt/lists/*

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"

RUN unzip awscliv2.zip
RUN ./aws/install

ENV EDITOR="vim"

RUN mkdir /webapp
WORKDIR /webapp

ENTRYPOINT ["./containers/rails/entrypoint.sh"]
```

3. Enter the running container
`docker-compose exec app /bin/bash`

4. Inside the container, run:
```
gem install bundler
bundle install
```

### What actually happened?

The command failed with the following error message:

```
root@312a25e45b5f:/webapp# bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bootsnap-1.7.2 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.2
Ignoring byebug-11.1.3 because its extensions are not built. Try: gem pristine byebug --version 11.1.3
...
Ignoring puma-4.3.7 because its extensions are not built. Try: gem pristine puma --version 4.3.7
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring unf_ext-0.0.7.7 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.7
Ignoring websocket-driver-0.7.3 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.3
/usr/local/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: /usr/local/bundle/gems/psych-3.3.1/lib/psych.so: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/psych-3.3.1/lib/psych.so
Traceback (most recent call last):
        48: from /usr/local/bin/bundle:23:in `<main>'
  ...
         3: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         2: from /usr/local/bundle/gems/psych-3.3.1/lib/psych.rb:13:in `<top (required)>'
         1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': /usr/local/bundle/gems/psych-3.3.1/lib/psych.so: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/psych-3.3.1/lib/psych.so (LoadError)

```
